# Generated by Django 2.2.1 on 2019-05-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subject11', models.CharField(max_length=20, null=True)),
                ('subject12', models.CharField(max_length=20, null=True)),
                ('subject13', models.CharField(max_length=20, null=True)),
                ('subject14', models.CharField(max_length=20, null=True)),
                ('subject15', models.CharField(max_length=20, null=True)),
                ('subject21', models.CharField(max_length=20, null=True)),
                ('subject22', models.CharField(max_length=20, null=True)),
                ('subject23', models.CharField(max_length=20, null=True)),
                ('subject24', models.CharField(max_length=20, null=True)),
                ('subject25', models.CharField(max_length=20, null=True)),
                ('subject31', models.CharField(max_length=20, null=True)),
                ('subject32', models.CharField(max_length=20, null=True)),
                ('subject33', models.CharField(max_length=20, null=True)),
                ('subject34', models.CharField(max_length=20, null=True)),
                ('subject35', models.CharField(max_length=20, null=True)),
                ('subject41', models.CharField(max_length=20, null=True)),
                ('subject42', models.CharField(max_length=20, null=True)),
                ('subject43', models.CharField(max_length=20, null=True)),
                ('subject44', models.CharField(max_length=20, null=True)),
                ('subject45', models.CharField(max_length=20, null=True)),
                ('subject51', models.CharField(max_length=20, null=True)),
                ('subject52', models.CharField(max_length=20, null=True)),
                ('subject53', models.CharField(max_length=20, null=True)),
                ('subject54', models.CharField(max_length=20, null=True)),
                ('subject55', models.CharField(max_length=20, null=True)),
                ('subject61', models.CharField(max_length=20, null=True)),
                ('subject62', models.CharField(max_length=20, null=True)),
                ('subject63', models.CharField(max_length=20, null=True)),
                ('subject64', models.CharField(max_length=20, null=True)),
                ('subject65', models.CharField(max_length=20, null=True)),
                ('subject71', models.CharField(max_length=20, null=True)),
                ('subject72', models.CharField(max_length=20, null=True)),
                ('subject73', models.CharField(max_length=20, null=True)),
                ('subject74', models.CharField(max_length=20, null=True)),
                ('subject75', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
